---
name: Book tests

on:
  push:
    branches:
      main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ottg:latest
          outputs: type=docker,dest=/tmp/ottg.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ottg
          path: /tmp/ottg.tar

  use:
    runs-on: ubuntu-latest
    steps:

  chapter-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        test_chapter: [
          test_chapter_01,
          test_chapter_02_unittest,
          test_chapter_03_unit_test_first_view,
          test_chapter_04_philosophy_and_refactoring,
          test_chapter_05_post_and_database,
          test_chapter_06_explicit_waits_1,
          test_chapter_07_working_incrementally,
          test_chapter_08_prettification,
          # test_chapter_09_docker,
          # test_chapter_10_production_readiness,
          # test_chapter_11_ansible,
          test_chapter_12_organising_test_files,
          test_chapter_13_database_layer_validation,
          test_chapter_14_simple_form,
          unit-test
        ]
    steps:
      - name: Download docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: ottg
          path: /tmp
      - name: Load docker image
        run: |
          docker load --input /tmp/ottg.tar
          docker image ls -a
      - uses: actions/checkout@v4
      - id: foo
        uses: hjwp/github-actions@v5
        with:
          test_chapter: ${{ matrix.test_chapter }}
